### ISSUE TITLE
Causal mask applied to attention scores

### ISSUE THREAD

**Issue by Li-XYi** [yingyichen-cyy/PrimalAttention#1]
Thanks for your remarkable work! 

I was wondering how to apply a causal mask, used in LLMs (such as lower triangular mask matrix), to attention scores without causal leakage?

**Comment by yingyichen-cyy** [comment]
Hi Li, thank you for your interest in our work! 
You can find our causal version of primal-attention in [/PrimalAttention_NLP/fairseq/modules/primal_attention.py#L239-L245](https://github.com/yingyichen-cyy/PrimalAttention/blob/481406f4d8cdacf8d12496eee5a1a4981d9e19ac/PrimalAttention_NLP/fairseq/modules/primal_attention.py#L239-L245).
We also provide a clear path of how to modify the ``fairseq`` package with our primal-attention in [/PrimalAttention_NLP/README.md](https://github.com/yingyichen-cyy/PrimalAttention/blob/master/PrimalAttention_NLP/README.md)
Hope these can be helpful for your works.
